# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=4)),
                ('signature', models.CharField(max_length=80)),
                ('role', models.IntegerField()),
            ],
        ),
    ]
